# Generated by Django 4.0.5 on 2022-06-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0003_agendamento_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='observacao',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
