# Generated by Django 4.0.5 on 2022-06-29 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0004_alter_agendamento_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='dia',
            field=models.ForeignKey(choices=[('S', 'Segunda'), ('T', 'Terça'), ('Q', 'Quarta'), ('QI', 'Quinta'), ('SE', 'Sexta'), ('SA', 'Sabado'), ('D', 'Domingo')], on_delete=django.db.models.deletion.DO_NOTHING, to='negocio.dia'),
        ),
    ]
